# .github/workflows/run-main.yml
name: Run main.py
# on:
#   schedule:
#     - cron: '0 0/6 * * *'
#   push:
#     branches:
#       - main  # or your default branch

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or any version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # if needed

      - name: Run main.py
        run: python main.py
